[package]
name = "accountant"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
sqlite = "0.37.0"
inquire = { version = "0.7.5", features = ["date"] }
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
